[workspace]
members = ["service", "program-keccak-inclusion", "common"]
resolver = "2"

[workspace.dependencies]
celestia-types = {git="https://github.com/eigerco/lumina.git"}
celestia-rpc = {git="https://github.com/eigerco/lumina.git"}
nmt-rs = "*"
sp1-zkvm = {version="3.4.0", features=["verify"]}