[package]
name = "eq-common"
version = "0.1.0"
edition = "2021"

[dependencies]
celestia-types = {workspace = true}
nmt-rs = {workspace = true}
serde = {workspace = true}
tendermint = {workspace = true}
tendermint-proto = {workspace = true}
sha3 = {workspace = true}
thiserror = {workspace = true}